#!/usr/bin/python

import random
from math import *
import sys

factor = float(sys.argv[1])

f = open('config','w')
f.write('12\n\n')
for i in range(0,12):
	x = 1
	y = 1
	for j in range(1,100):
		x = random.random()
	while (sqrt(x*x + y*y) > 1):
		x = 2.*(0.5-random.random())
		y = 2.*(0.5-random.random())
	z = sqrt(1-(x*x+y*y))
	if random.random() > 0.5:
		z = -z
	print str(i)
	f.write('H ' + str(factor*x) + ' ' + str(factor*y) + ' ' + str(factor*z) + '\n')
	
f.close()
